name: renju-app # placeholder name
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/litoprobka/renju-app#readme
license: BSD2
author: Litoprobka
#maintainer:          example@example.com
copyright: 2021 Litoprobka
#category:
extra-source-files:
  - README.md

language: GHC2021

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - StrictData

dependencies:
  - name: base
    mixin:
      - hiding (System.IO.Unsafe)
    version: ">= 4.8 && < 5"
  - aeson
  - aeson-pretty
  - async
  - atomic-write
  - bytestring
  - bytestring-to-vector
  - data-default
  - directory
  - file-embed
  - filepath
  - flow
  - ilist
  - JuicyPixels
  - lens
  - monomer
  - process
  - relude
  - template-haskell
  - text
  - tinyfiledialogs
  - unordered-containers

executables:
  renju-app:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -W
      - -threaded
      - -O2

library: # seems like I have to do this for hspec
  source-dirs: src
  ghc-options:
    - -W

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: renju-app
