name: renju-app # placeholder name
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/litoprobka/renju-app#readme
license: BSD2
author: Litoprobka
#maintainer:          example@example.com
copyright: 2021 Litoprobka
#category:
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - StrictData

dependencies:
  - name: base
    mixin:
      - hiding (System.IO.Unsafe)
    version: ">= 4.8 && < 5"
  - aeson
  - aeson-pretty
  - atomic-write
  - bytestring
  - data-default
  - directory
  - filepath
  - flow
  - Hclip
  - hsinstall
  - ilist
  - lens
  - monomer
  - process
  - relude
  - text
  - tinyfiledialogs
  - unordered-containers
  - vector
  - vector-sized

executables:
  app:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -W
      - -threaded

library: # seems like I have to do this for hspec
  source-dirs: src
  ghc-options:
    - -W

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: renju-app
